"""Cell-type colours for the H&E overlay figure -- edit this dict to tweak.

Generated by make_he_palette.py: hue set by group along the hues that can clear
0.12 from the measured H&E stain, chroma 90% of the sRGB maximum at
each colour's lightness and hue, lightness alternating [0.55, 0.75, 0.65] ([0.72, 0.9, 0.81] over
the yellow/olive band 70-125 deg, where dark reads brown).
"""

BACKGROUND = '#ad6fa0'   # mean sampled H&E tissue pixel

HE_CELLTYPE_COLORS = {
    # epithelial
    'Tumor_epi': '#f36e2a',
    'Alveolar_epi': '#f89031',
    'Airway_epi': '#f9b04b',
    # vascular/stromal
    'Vas_Endo': '#bba52e',
    'Lym_Endo': '#e2e942',
    'Pericyte': '#799e27',
    'SMC': '#34871e',
    'Fibro': '#38cd73',
    # lymphoid
    'T': '#2da492',
    'NK': '#218180',
    'B': '#38c2d4',
    'Plasma': '#2c9dbe',
    # myeloid
    'pDC': '#2079bf',
    'cDC': '#0d42aa',
    'Langhans_cell': '#4225e3',
    'Macro': '#7842f1',
    'Myeloid_other': '#9b44f2',
    'Neutro': '#c73ff4',
    'Mast': '#f73bef',
}
